### ISSUE TITLE
Area of the catchement issue

### ISSUE THREAD

**Issue by marcellevarg** [inrae/airGRiwrm#1]
First, I would like to congratulate the developers, airGRiwrm is an excellent package with many explanatory examples!

I have a question in hydrological terms, when I try to run the model for my basin, I get the following message:
**Area of the catchment X must be greater than the sum of the area of its upstream catchments.**

I don't understand why this needs to be true, because there is the possibility of larger basins draining into smaller ones.
If you can solve this doubt of mine, I would be very grateful.

**Comment by DDorch** [comment]
The `area` column of the `GRiwrm` must be filled with the total catchment area. So downstream catchments necessarily have an area larger than the upstream ones.

**Comment by marcellevarg** [comment]
Thanks for the answer! Now I understand how the model was structured.

I have another question, is it possible to calibrate the GR2M in a semi-distributed way?

**Comment by DDorch** [comment]
> 1.  Is it possible to calibrate the GR2M in a semi-distributed way?

Not yet. The limitation comes from airGR on which airGRiwrm relies. I have opened a ticket in our gitlab repository: https://gitlab.irstea.fr/in-wop/airGRiwrm/-/issues/112. I can't give you a delay for the implementation of GR2M but if you are a bit familiar with R package development, I encourage you to try to remove this limitation and propose your solution :)

> 2. Is the distance between the nodes the length of the flood wave propagation channel?

The semi-distribution relies on a "lag" model which applies a constant delay on the simulated flow between upstream and downstream nodes. For a downstream node receiving the flow of several upstream nodes this delay is calculated from one constant propagation speed (the so-called "mean flow velocity" parameter of the Lag model - see `airGR::RunModel_Lag` in the R console). Therefore, the length between the nodes is used for the delay calculation between each nodes with the formula : delay (s) = 1000 * distance between nodes (km) / propagation speed (m/s)

**Comment by marcellevarg** [comment]
Thank you for such complete answers!
Again, congratulations on the excellent development.
